### ISSUE TITLE
Fails to build on rustc/cargo 1.77.2

### ISSUE THREAD

**Issue by ohbe1jacobi** [meew0/namida#7]
```
error[E0425]: cannot find function `size_of` in this scope
    --> src/client/get.rs:372:41
     |
 372 |                 const U64_SIZE: usize = size_of::<u64>();
     |                                         ^^^^^^^ not found in this scope
     |
 help: consider importing one of these items
     |
 1   + use core::mem::size_of;
     |
 1   + use std::mem::size_of;
```

Issue does not exist on 1.80+.  Suggest following patch for backwards compatibility

```
diff --git a/src/client/get.rs b/src/client/get.rs
index 5e38e02..27355fa 100644
--- a/src/client/get.rs
+++ b/src/client/get.rs
@@ -3,6 +3,7 @@ use std::{
     path::{Path, PathBuf},
     sync::Arc,
     time::Instant,
+    mem::size_of,
 };
 
 use anyhow::bail;
```
